package com.ras.crypto

import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test

/**
 * Cross-platform test vectors for pairing HMAC functions.
 *
 * These vectors are generated by the daemon's Python implementation and embedded
 * here to verify the Android implementation produces identical output.
 *
 * Source: test-vectors/pairing.json
 */
class PairHmacVectorsTest {

    // -- Test vector data (from test-vectors/pairing.json) --

    data class PairVector(
        val id: String,
        val masterSecretHex: String,
        val authKeyHex: String,
        val sessionId: String,
        val deviceId: String,
        val nonceHex: String,
        val expectedRequestHmacHex: String,
        val expectedResponseHmacHex: String,
    )

    companion object {
        val VECTORS = listOf(
            PairVector(
                id = "pair_hmac_basic",
                masterSecretHex = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
                authKeyHex = "bec0c3289e346d890ea330014e23e6e7cf95f82c8bd7f5f133850c89ac165a43",
                sessionId = "sess-abc123",
                deviceId = "phone-123",
                nonceHex = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                expectedRequestHmacHex = "1d8923b686f3ef703914245033cd8a328f2dc695473244a68c2a6ebd41d5eb77",
                expectedResponseHmacHex = "ec5185abcc0633e934d7466f3566fa55f0f353bf8780a52bcc9cda72d3ecfbf0",
            ),
            PairVector(
                id = "pair_hmac_different_inputs",
                masterSecretHex = "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
                authKeyHex = "3a398ba492673e7117367f7f48bb6d1c1dab121288c6db63729159b0db0eb74d",
                sessionId = "sess-xyz789",
                deviceId = "pixel-456",
                nonceHex = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                expectedRequestHmacHex = "680a2680db2068a50e523122064fc465befd34bee52b3c6f8e689081508a5862",
                expectedResponseHmacHex = "66c71ee7826074fea5a08c62d4cd7d1389f4617d5f84b11acbe0acb51c539c67",
            ),
            PairVector(
                id = "pair_hmac_empty_device_id",
                masterSecretHex = "4242424242424242424242424242424242424242424242424242424242424242",
                authKeyHex = "6f25df315ce85acf7305b2e25ed2d395f3986fe72bce68e602507c2a2a47240e",
                sessionId = "sess-empty",
                deviceId = "",
                nonceHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
                expectedRequestHmacHex = "a2be401e3d681538eaa07b30a03f8375fac9e4abf73a6b73ffc326840de8ff68",
                expectedResponseHmacHex = "614bd5b0899a361195f86993e558c0ef3e3ff0b6ada1d3198541b99f0b524425",
            ),
        )
    }

    @Tag("unit")
    @Test
    fun `pair request HMAC matches daemon test vector`() {
        for (v in VECTORS) {
            val authKey = v.authKeyHex.hexToBytes()
            val nonce = v.nonceHex.hexToBytes()

            val result = HmacUtils.computePairRequestHmac(
                authKey = authKey,
                sessionId = v.sessionId,
                deviceId = v.deviceId,
                nonce = nonce,
            )

            assertEquals(
                v.expectedRequestHmacHex,
                result.toHex(),
                "Request HMAC mismatch for vector '${v.id}'",
            )
        }
    }

    @Tag("unit")
    @Test
    fun `pair response HMAC matches daemon test vector`() {
        for (v in VECTORS) {
            val authKey = v.authKeyHex.hexToBytes()
            val nonce = v.nonceHex.hexToBytes()

            val result = HmacUtils.computePairResponseHmac(
                authKey = authKey,
                nonce = nonce,
            )

            assertEquals(
                v.expectedResponseHmacHex,
                result.toHex(),
                "Response HMAC mismatch for vector '${v.id}'",
            )
        }
    }

    @Tag("unit")
    @Test
    fun `auth key derivation matches daemon`() {
        for (v in VECTORS) {
            val masterSecret = v.masterSecretHex.hexToBytes()

            val derivedKey = KeyDerivation.deriveKey(masterSecret, "auth")

            assertEquals(
                v.authKeyHex,
                derivedKey.toHex(),
                "Auth key derivation mismatch for vector '${v.id}'",
            )
        }
    }

    @Tag("unit")
    @Test
    fun `PAIR_NONCE_LENGTH is 32`() {
        assertEquals(32, HmacUtils.PAIR_NONCE_LENGTH)
    }
}
