# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: terminal.proto
# plugin: python-betterproto
# This file has been @generated
#
# Re-export all proto classes for convenient imports
# (Classes from ras.py are also exported here)

from dataclasses import dataclass

import betterproto

# Re-export classes from ras.py (auth, ntfy, sessions, signaling)
from .ras import (
    Agent,
    AgentsListEvent,
    AuthChallenge,
    AuthEnvelope,
    AuthError,
    AuthErrorErrorCode,
    AuthResponse,
    AuthSuccess,
    AuthVerify,
    CreateSessionCommand,
    DirectoriesListEvent,
    DirectoryEntry,
    GetAgentsCommand,
    GetDirectoriesCommand,
    IpChangeNotification,
    KillSessionCommand,
    ListSessionsCommand,
    QrPayload,
    RefreshAgentsCommand,
    RenameSessionCommand,
    Session,
    SessionActivityEvent,
    SessionCommand,
    SessionCreatedEvent,
    SessionErrorEvent,
    SessionEvent,
    SessionKilledEvent,
    SessionListEvent,
    SessionRenamedEvent,
    SessionStatus,
    SignalError,
    SignalErrorErrorCode,
    SignalRequest,
    SignalResponse,
)


class KeyType(betterproto.Enum):
    KEY_UNKNOWN = 0
    KEY_ENTER = 1
    """Basic"""

    KEY_TAB = 2
    KEY_BACKSPACE = 3
    KEY_ESCAPE = 4
    KEY_DELETE = 5
    KEY_INSERT = 6
    KEY_UP = 10
    """Arrows"""

    KEY_DOWN = 11
    KEY_LEFT = 12
    KEY_RIGHT = 13
    KEY_HOME = 20
    """Navigation"""

    KEY_END = 21
    KEY_PAGE_UP = 22
    KEY_PAGE_DOWN = 23
    KEY_F1 = 30
    """Function keys"""

    KEY_F2 = 31
    KEY_F3 = 32
    KEY_F4 = 33
    KEY_F5 = 34
    KEY_F6 = 35
    KEY_F7 = 36
    KEY_F8 = 37
    KEY_F9 = 38
    KEY_F10 = 39
    KEY_F11 = 40
    KEY_F12 = 41
    KEY_CTRL_C = 50
    """Control characters (sent as special keys for clarity)"""

    KEY_CTRL_D = 51
    KEY_CTRL_Z = 52


@dataclass(eq=False, repr=False)
class TerminalOutput(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    data: bytes = betterproto.bytes_field(2)
    sequence: int = betterproto.uint64_field(3)
    partial: bool = betterproto.bool_field(4)


@dataclass(eq=False, repr=False)
class TerminalInput(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    data: bytes = betterproto.bytes_field(2, group="input")
    special: "SpecialKey" = betterproto.message_field(3, group="input")
    resize: "TerminalResize" = betterproto.message_field(4, group="input")


@dataclass(eq=False, repr=False)
class SpecialKey(betterproto.Message):
    key: "KeyType" = betterproto.enum_field(1)
    modifiers: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class TerminalResize(betterproto.Message):
    cols: int = betterproto.uint32_field(1)
    rows: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class TerminalCommand(betterproto.Message):
    attach: "AttachTerminal" = betterproto.message_field(1, group="command")
    detach: "DetachTerminal" = betterproto.message_field(2, group="command")
    input: "TerminalInput" = betterproto.message_field(3, group="command")


@dataclass(eq=False, repr=False)
class AttachTerminal(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    from_sequence: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class DetachTerminal(betterproto.Message):
    session_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class TerminalEvent(betterproto.Message):
    output: "TerminalOutput" = betterproto.message_field(1, group="event")
    attached: "TerminalAttached" = betterproto.message_field(2, group="event")
    detached: "TerminalDetached" = betterproto.message_field(3, group="event")
    error: "TerminalError" = betterproto.message_field(4, group="event")
    skipped: "OutputSkipped" = betterproto.message_field(5, group="event")


@dataclass(eq=False, repr=False)
class TerminalAttached(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    cols: int = betterproto.uint32_field(2)
    rows: int = betterproto.uint32_field(3)
    buffer_start_seq: int = betterproto.uint64_field(4)
    current_seq: int = betterproto.uint64_field(5)


@dataclass(eq=False, repr=False)
class TerminalDetached(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class TerminalError(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    error_code: str = betterproto.string_field(2)
    message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class OutputSkipped(betterproto.Message):
    session_id: str = betterproto.string_field(1)
    from_sequence: int = betterproto.uint64_field(2)
    to_sequence: int = betterproto.uint64_field(3)
    bytes_skipped: int = betterproto.uint32_field(4)
