# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qr_payload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qr_payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10qr_payload.proto\x12\x03ras\"\xc5\x01\n\tQrPayload\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x15\n\rmaster_secret\x18\x04 \x01(\x0c\x12\x12\n\nsession_id\x18\x05 \x01(\t\x12\x12\n\nntfy_topic\x18\x06 \x01(\t\x12\x14\n\x0ctailscale_ip\x18\x07 \x01(\t\x12\x16\n\x0etailscale_port\x18\x08 \x01(\r\x12\x0e\n\x06vpn_ip\x18\t \x01(\t\x12\x10\n\x08vpn_port\x18\n \x01(\rB\x17\n\rcom.ras.protoP\x01\xba\x02\x03RASb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qr_payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.ras.protoP\001\272\002\003RAS'
  _globals['_QRPAYLOAD']._serialized_start=26
  _globals['_QRPAYLOAD']._serialized_end=223
# @@protoc_insertion_point(module_scope)
