# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: clipboard.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class ErrorCode(betterproto.Enum):
    ERROR_CODE_UNSPECIFIED = 0
    ERROR_CODE_SIZE_EXCEEDED = 1
    ERROR_CODE_INVALID_FORMAT = 2
    ERROR_CODE_TRANSFER_IN_PROGRESS = 3
    ERROR_CODE_INVALID_CHUNK = 4
    ERROR_CODE_CHUNK_MISSING = 5
    ERROR_CODE_TRANSFER_TIMEOUT = 6
    ERROR_CODE_CLIPBOARD_UNAVAILABLE = 7
    ERROR_CODE_CLIPBOARD_FAILED = 8
    ERROR_CODE_PASTE_FAILED = 9
    ERROR_CODE_NO_SESSION = 10
    ERROR_CODE_CANCELLED = 11


class ImageFormat(betterproto.Enum):
    IMAGE_FORMAT_UNSPECIFIED = 0
    IMAGE_FORMAT_JPEG = 1
    IMAGE_FORMAT_PNG = 2
    IMAGE_FORMAT_GIF = 3
    IMAGE_FORMAT_WEBP = 4


class ContentType(betterproto.Enum):
    CONTENT_TYPE_UNSPECIFIED = 0
    CONTENT_TYPE_IMAGE = 1
    CONTENT_TYPE_TEXT = 2


@dataclass
class ImageStart(betterproto.Message):
    """Start an image transfer"""

    transfer_id: str = betterproto.string_field(1)
    total_size: int = betterproto.int64_field(2)
    format: "ImageFormat" = betterproto.enum_field(3)
    total_chunks: int = betterproto.int32_field(4)


@dataclass
class ImageChunk(betterproto.Message):
    """Image chunk data"""

    transfer_id: str = betterproto.string_field(1)
    index: int = betterproto.int32_field(2)
    data: bytes = betterproto.bytes_field(3)


@dataclass
class ImageCancel(betterproto.Message):
    """Cancel an image transfer"""

    transfer_id: str = betterproto.string_field(1)


@dataclass
class TextPaste(betterproto.Message):
    """Text to paste (size <= threshold, no approval needed)"""

    text: str = betterproto.string_field(1)


@dataclass
class TextPasteApproved(betterproto.Message):
    """Text to paste after user approval (size > threshold)"""

    text: str = betterproto.string_field(1)


@dataclass
class Progress(betterproto.Message):
    """Transfer progress update"""

    transfer_id: str = betterproto.string_field(1)
    received_chunks: int = betterproto.int32_field(2)
    total_chunks: int = betterproto.int32_field(3)
    received_bytes: int = betterproto.int64_field(4)
    total_bytes: int = betterproto.int64_field(5)


@dataclass
class Complete(betterproto.Message):
    """Transfer/paste completed successfully"""

    transfer_id: str = betterproto.string_field(1)
    content_type: "ContentType" = betterproto.enum_field(2)


@dataclass
class ApprovalRequired(betterproto.Message):
    """Large text requires user approval"""

    size: int = betterproto.int64_field(1)
    preview: str = betterproto.string_field(2)


@dataclass
class Error(betterproto.Message):
    """Error occurred"""

    transfer_id: str = betterproto.string_field(1)
    code: "ErrorCode" = betterproto.enum_field(2)
    message: str = betterproto.string_field(3)


@dataclass
class Cancelled(betterproto.Message):
    """Transfer was cancelled"""

    transfer_id: str = betterproto.string_field(1)


@dataclass
class ClipboardMessage(betterproto.Message):
    """All clipboard messages wrapped in oneof"""

    # Phone -> Daemon
    image_start: "ImageStart" = betterproto.message_field(1, group="payload")
    image_chunk: "ImageChunk" = betterproto.message_field(2, group="payload")
    image_cancel: "ImageCancel" = betterproto.message_field(3, group="payload")
    text_paste: "TextPaste" = betterproto.message_field(4, group="payload")
    text_paste_approved: "TextPasteApproved" = betterproto.message_field(
        5, group="payload"
    )
    # Daemon -> Phone
    progress: "Progress" = betterproto.message_field(10, group="payload")
    complete: "Complete" = betterproto.message_field(11, group="payload")
    approval_required: "ApprovalRequired" = betterproto.message_field(
        12, group="payload"
    )
    error: "Error" = betterproto.message_field(13, group="payload")
    cancelled: "Cancelled" = betterproto.message_field(14, group="payload")
