# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: clipboard.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class ErrorCode(betterproto.Enum):
    UNSPECIFIED = 0
    SIZE_EXCEEDED = 1
    INVALID_FORMAT = 2
    TRANSFER_IN_PROGRESS = 3
    INVALID_CHUNK = 4
    CHUNK_MISSING = 5
    TRANSFER_TIMEOUT = 6
    CLIPBOARD_UNAVAILABLE = 7
    CLIPBOARD_FAILED = 8
    PASTE_FAILED = 9
    NO_SESSION = 10
    CANCELLED = 11


class ImageFormat(betterproto.Enum):
    UNSPECIFIED = 0
    JPEG = 1
    PNG = 2
    GIF = 3
    WEBP = 4


class ContentType(betterproto.Enum):
    UNSPECIFIED = 0
    IMAGE = 1
    TEXT = 2


@dataclass(eq=False, repr=False)
class ImageStart(betterproto.Message):
    """Start an image transfer"""

    transfer_id: str = betterproto.string_field(1)
    total_size: int = betterproto.int64_field(2)
    format: "ImageFormat" = betterproto.enum_field(3)
    total_chunks: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class ImageChunk(betterproto.Message):
    """Image chunk data"""

    transfer_id: str = betterproto.string_field(1)
    index: int = betterproto.int32_field(2)
    data: bytes = betterproto.bytes_field(3)


@dataclass(eq=False, repr=False)
class ImageCancel(betterproto.Message):
    """Cancel an image transfer"""

    transfer_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class TextPaste(betterproto.Message):
    """Text to paste (size <= threshold, no approval needed)"""

    text: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class TextPasteApproved(betterproto.Message):
    """Text to paste after user approval (size > threshold)"""

    text: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class Progress(betterproto.Message):
    """Transfer progress update"""

    transfer_id: str = betterproto.string_field(1)
    received_chunks: int = betterproto.int32_field(2)
    total_chunks: int = betterproto.int32_field(3)
    received_bytes: int = betterproto.int64_field(4)
    total_bytes: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class Complete(betterproto.Message):
    """Transfer/paste completed successfully"""

    transfer_id: str = betterproto.string_field(1)
    content_type: "ContentType" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class ApprovalRequired(betterproto.Message):
    """Large text requires user approval"""

    size: int = betterproto.int64_field(1)
    preview: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Error(betterproto.Message):
    """Error occurred"""

    transfer_id: str = betterproto.string_field(1)
    code: "ErrorCode" = betterproto.enum_field(2)
    message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class Cancelled(betterproto.Message):
    """Transfer was cancelled"""

    transfer_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ClipboardMessage(betterproto.Message):
    """All clipboard messages wrapped in oneof"""

    image_start: "ImageStart" = betterproto.message_field(1, group="payload")
    """Phone -> Daemon"""

    image_chunk: "ImageChunk" = betterproto.message_field(2, group="payload")
    image_cancel: "ImageCancel" = betterproto.message_field(3, group="payload")
    text_paste: "TextPaste" = betterproto.message_field(4, group="payload")
    text_paste_approved: "TextPasteApproved" = betterproto.message_field(
        5, group="payload"
    )
    progress: "Progress" = betterproto.message_field(10, group="payload")
    """Daemon -> Phone"""

    complete: "Complete" = betterproto.message_field(11, group="payload")
    approval_required: "ApprovalRequired" = betterproto.message_field(
        12, group="payload"
    )
    error: "Error" = betterproto.message_field(13, group="payload")
    cancelled: "Cancelled" = betterproto.message_field(14, group="payload")
